version: "3.9"
services:
  one-frame:
    image: "paidyinc/one-frame"
    deploy:
      replicas: 10
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "one-frame"
  forex-proxy:
    build: .
    environment:
      - FX_PROXY_BASE_URL=http://nginx:4000
      - FX_PROXY_HTTP_TOKEN=10dc303535874aeccc86a8251e6992f5
      - FX_PROXY_HTTP_TIMEOUT=30
      - FX_PROXY_APP_PORT=7070
      - FX_PROXY_APP_SECRET=d623ec59-118f-4e8c-a874-653b127af546
    ports:
      - "7070:7070"
    depends_on:
      - "nginx"